config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  get "performances/search"
  resources :performances
  put "users/settings"

  resources :bookings, only: [:index, :create] do
    post "/confirm", to: "bookings#confirm"
    post "/reject", to: "bookings#reject"
  end
  get "bookings/my_bookings"
  get "bookings/my_performances"
end

app/models/booking.rb
class Booking < ApplicationRecord
  serialize :start_time, Tod::TimeOfDay
  serialize :end_time, Tod::TimeOfDay
  before_create :init_price

  belongs_to :performance
  belongs_to :client, :class_name => "User"
  belongs_to :actor, :class_name => "User"

  enum status: [:pending, :canceled, :confirmed]

  validates_presence_of :date, :start_time, :end_time
  validate :booking_date_cannot_be_in_past
  validate :actor_is_free
  validate :shift_is_in_working_time

  default_scope { order(date: :asc) }
  scope :my_upcoming_pending_events, ->(user) { where("client_id = ? AND date >= ? AND status = ? ", user.id, Date.today, 0) }
  scope :my_upcoming_canceled_events, ->(user) { where("client_id = ? AND date >= ? AND status = ? ", user.id, Date.today, 1) }
  scope :my_upcoming_confirmed_events, ->(user) { where("client_id = ? AND date >= ? AND status = ? ", user.id, Date.today, 2) }

  scope :my_upcoming_pending_performances, ->(user) { where("actor_id = ? AND date >= ? AND status = ? ", user.id, Date.today, 0) }
  scope :my_upcoming_canceled_performances, ->(user) { where("actor_id = ? AND date >= ? AND status = ? ", user.id, Date.today, 1) }
  scope :my_upcoming_confirmed_performances, ->(user) { where("actor_id = ? AND date >= ? AND status = ? ", user.id, Date.today, 2) }

  private

  def booking_date_cannot_be_in_past
    if date.present? && date < Date.today
      errors.add(:date, "can't be in the past")
    end
  end

  def shift_is_in_working_time
    work_shift_time = Tod::Shift.new(Tod::TimeOfDay(actor.availability_start_time), Tod::TimeOfDay(actor.availability_end_time))
    asked_shift_time = Tod::Shift.new(Tod::TimeOfDay(start_time), Tod::TimeOfDay(end_time))
    errors.add(:date, "This actor doesn't work in that shift") unless work_shift_time.contains?(asked_shift_time)
  end

  def actor_is_free
    actor_events = Booking.where("actor_id = ? AND date = ? AND status = ?", actor.id, date, 2)
    asked_shift_time = Tod::Shift.new(Tod::TimeOfDay(start_time), Tod::TimeOfDay(end_time), true)
    actor_is_available = actor_events.none? do |event|
      event_shift_time = Tod::Shift.new(Tod::TimeOfDay(event.start_time), Tod::TimeOfDay(event.end_time), true)
      event_shift_time.overlaps?(asked_shift_time)
    end

    errors.add(:date, "This actor is not free at that time") unless actor_is_available
  end

  def init_price
    duration = self.end_time - self.start_time
    hour_price = self.performance.price_per_hour
    self.price = duration.hour * hour_price
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  skip_after_action :verify_policy_scoped, :only => :index
  before_action :authenticate_user!

  def my_bookings
    authorize @pending_bookings = Booking.my_upcoming_pending_events(current_user)
    authorize @canceled_bookings = Booking.my_upcoming_canceled_events(current_user)
    authorize @confirmed_bookings = Booking.my_upcoming_confirmed_events(current_user)
  end

  def my_performances
    authorize @pending_performances = Booking.my_upcoming_pending_performances(current_user)
    authorize @canceled_performances = Booking.my_upcoming_canceled_performances(current_user)
    authorize @confirmed_performances = Booking.my_upcoming_confirmed_performances(current_user)
  end

  def index
    @bookings = current_user.bookings.includes(:performance)
  end

  # GET "restaurants/:restaurant_id/reviews/new" view cours 1.22
  def new
    @performance = Performance.find(params[:performance_id])
    @user = User.find(params[:user_id])
    @booking = @performance.bookings.new
  end

  # POST "restaurants/:restaurant_id/reviews" view cours 1.33
  def create
    @performance = Performance.find(params[:booking][:performance_id].to_i)
    authorize @booking = Booking.new()
    @booking.client = current_user
    @booking.performance = @performance
    @booking.actor = @performance.user
    @booking.date = params[:booking][:date]
    @booking.start_time = params[:booking]["start_time(4i)"].to_i
    @booking.end_time = params[:booking]["end_time(4i)"].to_i

    if @booking.save
      flash[:success] = "This slot has been registered for you!"
      redirect_to bookings_my_bookings_path
    else
      flash[:alert] = @booking.errors.full_messages
      redirect_back fallback_location: performance_path(@performance)
    end
  end

  def confirm
    authorize @booking = Booking.find(params[:booking_id])
    @booking.status = 2
    if @booking.valid?
      @booking.confirmed!
    else
      @booking.status = 1
      @booking.save(validate: false)
      flash[:warning] = "Booking got canceled cause you are no more available at that time"
    end

    redirect_to bookings_my_performances_path
  end

  def reject
    authorize @booking = Booking.find(params[:booking_id])
    @booking.canceled!
    redirect_to bookings_my_performances_path
  end
end

app/views/bookings/_booking_card.html.erb
<div class="card-trip m-4 position-relative">
  <div class="container my-4 d-flex justify-content-between align-items-start">
    <div>
      <h3><%= booking.performance.character.name %> </h3>
      <h5>Played by <%= "@#{booking.actor.nickname}" %> </h5>
    </div>
    <% if booking.pending? %>
      <i class="fas fa-hourglass-half text-warning text-big" style="top: 10px; right: 10px;"></i>
    <% elsif booking.confirmed? %>
      <i class="fas fa-check-circle text-success text-big" style="top: 10px; right: 10px;"></i>
    <% elsif booking.canceled? %>
      <i class="fas fa-times-circle text-danger text-big" style="top: 10px; right: 10px;"></i>
    <% end %>
  </div>
  <%= cl_image_tag booking.performance.photo.key %>
  <div class="card-trip-infos">
    <div class="card-trip-description">
      <p>Address: <%= booking.performance.location.address %></p>
      <p>Date: <%= booking.date.strftime("%a, %d %B %Y") %></p>
      <p>
        From: <%= booking.start_time.strftime("%I:%M %p") %>
        to: <%= booking.end_time.strftime("%I:%M %p") %>
      </p>
      <h2 class="card-trip-pricing mt-1">Total cost: <%= booking.price %> CHF</h2>
    </div>
    <%= cl_image_tag(booking.performance.user.photo.key, width: 150, height: 150, crop: :thumb, gravity: :face, class: "avatar-bordered") %>
  </div>
</div>

app/views/bookings/_form.html.erb
<div class="col-md-4 col-xs-12 booking-scroll">
  <div class="performance-show-card">
    <h3>Book your performance now!</h3> 
    <%= simple_form_for [@booking], method: "post" do |f| %>
      <%= f.association :performance, as: :hidden, input_html: { value: @performance.id } %>
      <%= f.input :date, as: :string,
                         input_html: { class: "datepicker" },
                         placeholder: "Pick a date" %>
      <%= f.input :start_time, { prompt: "Choose an hour", label: "Start hour", discard_minute: true } %>
      <%= f.input :end_time, { prompt: "Choose an hour", label: "End hour", discard_minute: true } %>
      <%= f.input "Price/hour", input_html: { value: "#{@performance.price_per_hour} CHF", disabled: true } %>
      <%= f.input "Price", input_html: { value: "0 CHF", disabled: true } %>
      <%= f.submit "Book", class: "btn btn-primary mt-3 disable disabled", id: "submit-button" %>
    <% end %>
  </div>
</div>

app/views/bookings/_performance_card.html.erb
<div class="card-trip m-4 position-relative">

  <% if booking.pending? && current_user == booking.actor %>
    <div class="" id="buttons-booking">
      <%= link_to booking_reject_path(booking), method: "post", remote: true do %>
        <button class="btn btn-danger btn-lg position-absolute m-4" id="btn-reject" style="top:75px;left:0;">Reject</button>
      <% end %>
      <%= link_to booking_confirm_path(booking), method: "post", remote: true do %>
        <button class="btn btn-success btn-lg position-absolute m-4" id="btn-confirm" style="top:75px;right:0;">Accept</button>
      <% end %>
    </div>
  <% end %>

  <div class="container my-4 d-flex justify-content-between align-items-start">
    <div>
      <h3><%= booking.performance.character.name %> </h3>
      <h5>Hired by <%= "@#{booking.client.nickname}" %> </h5>
    </div>
    <% if booking.pending? %>
      <i class="fas fa-hourglass-half text-warning text-big" id="booking-to-confirm" style="top: 10px; right: 10px;"></i>
    <% elsif booking.confirmed? %>
      <i class="fas fa-check-circle text-success text-big" style="top: 10px; right: 10px;"></i>
    <% elsif booking.canceled? %>
      <i class="fas fa-times-circle text-danger text-big" style="top: 10px; right: 10px;"></i>
    <% end %>
  </div>
  <%= cl_image_tag booking.performance.photo.key %>
  <div class="card-trip-infos">
    <div class="card-trip-description">
      <p>Address: <%= booking.performance.location.address %></p>
      <p>Date: <%= booking.date.strftime("%a, %d %B %Y") %></p>
      <p>
        From: <%= booking.start_time.strftime("%I:%M %p") %>
        to: <%= booking.end_time.strftime("%I:%M %p") %>
      </p>
      <h2 class="card-trip-pricing mt-1">Total cost: <%= booking.price %> CHF</h2>
    </div>
    <%= cl_image_tag(booking.performance.user.photo.key, width: 150, height: 150, crop: :thumb, gravity: :face, class: "avatar-bordered") %>
  </div>
</div>

app/views/bookings/my_bookings.html.erb
<div class="container my-4">
  <div class="bookings-list">
    <div class="container m-2">
      <h1>All my upcoming bookings</h1>
    </div>
    <div class="row">
      <div class="col-xs-12 col-lg-4 mt-2">
        <h2 class="mx-4 mt-4 mb-2 text-center">Confirmed</h2>
        <% @confirmed_bookings.each do |booking| %>
          <%= render partial: "booking_card", locals: { booking: booking } %>
        <% end %>
      </div>
      <div class="col-xs-12 col-lg-4 mt-2">
        <h2 class="mx-4 mt-4 mb-2 text-center">Pending</h2>
        <% @pending_bookings.each do |booking| %>
          <%= render partial: "booking_card", locals: { booking: booking } %>
        <% end %>
      </div>
      <div class="col-xs-12 col-lg-4 mt-2">
        <h2 class="mx-4 mt-4 mb-2 text-center">Canceled</h2>
        <% @canceled_bookings.each do |booking| %>
          <%= render partial: "booking_card", locals: { booking: booking } %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/my_performances.html.erb
<div class="container my-4">
  <div class="bookings-list mt-4">
    <div class="container m-2">
      <h1>All my upcoming performances</h1>
    </div>
    <div class="row pt-4 border-top">
      <div class="col-xs-12 col-lg-4 bg-info mt-2">
        <h2 class="mx-4 mt-4 mb-2 text-center">Awaiting <%= "action".pluralize(@pending_performances.count) %></h2>
        <% if @pending_performances %>
          <% @pending_performances.each do |booking| %>
            <%= render partial: "performance_card", locals: { booking: booking } %>
          <% end %>
        <% else %>
          <h2 class="mx-4 my-2">You don't have any new request</h2>
        <% end %>
      </div>
      <div class="col-xs-12 col-lg-4 mt-2">
        <h2 class="mx-4 mt-4 mb-2 text-center">Confirmed</h2>
        <% @confirmed_performances.each do |booking| %>
          <%= render partial: "performance_card", locals: { booking: booking } %>
        <% end %>
      </div>
      <div class="col-xs-12 col-lg-4 mt-2">
        <h2 class="mx-4 mt-4 mb-2 text-center">Canceled</h2>
        <% @canceled_performances.each do |booking| %>
          <%= render partial: "performance_card", locals: { booking: booking } %>
        <% end %>
      </div>
    </div>
  </div>
</div>