config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  get "performances/search"
  resources :performances
  put "users/settings"

  resources :bookings, only: [:index, :create] do
    post "/confirm", to: "bookings#confirm"
    post "/reject", to: "bookings#reject"
  end
  get "bookings/my_bookings"
  get "bookings/my_performances"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if success %>
  <div class="flash flash-success alert alert-dismissible fade show" role="alert">
    <span><strong>Yay!</strong> 🎉 </span>
    <%= sanitize success %>
    <a data-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

<% if warning %>
  <div class="flash flash-warning alert alert-dismissible fade show" role="alert">
    <span><strong>Mmh</strong> 🤔 </span>
    <%= warning %>
    <a data-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

<% if alert %>
  <div class="flash flash-danger alert alert-dismissible fade show" role="alert">
    <span><strong>Oops!</strong> 😱 </span>
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="bg-light text-center" id="footer">
  <div class="h-100 d-flex flex-column justify-content-around text-center border-top" style="background-color: #F7F7F7);">
    <div class="center-icon">
      <!-- Facebook -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #3b5998; color:white;"
        href="https://www.facebook.com/Le-Wagon-290420631559489" target="_blank"
        role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>

      <!-- Twitter -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #55acee; color:white;"
        href="https://twitter.com/search?q=actor%20swiss&src=typed_query" target="_blank"
        role="button"
        ><i class="fab fa-twitter"></i
      ></a>

      <!-- Google -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #dd4b39; color:white;"
        href="https://www.google.com/search?rlz=1C5CHFA_enCH911CH911&sxsrf=ALeKk03lXxopp693w3PxjD0sGdsoOo6BxQ:1614609735820&ei=O_08YOD2FdKDi-gPu-CM8AM&q=google%20th%C3%A9atre%20lausanne&oq=google+th%C3%A9atre+lausanne&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAELADEEM6BwgAEEcQsAM6AggAOgYIABAWEB46BQghEKABOgcIIRAKEKABOgQIIRAVOgUIABDNAjoGCAAQBxAeOgoIABAIEAcQChAeOggIABAIEAcQHlDlKVjUTWDhVWgBcAJ4AIAB-QKIAcoVkgEHNy43LjIuMpgBAKABAaoBB2d3cy13aXrIAQnAAQE&sclient=gws-wiz&ved=2ahUKEwjbi4T-qY_vAhVO2aQKHSJTCfEQvS4wAXoECAUQFA&uact=5&tbs=lf:1,lf_ui:1&tbm=lcl&rflfq=1&num=10&rldimm=5011719011781109502&lqi=Chhnb29nbGUgdGjDqWF0cmUgbGF1c2FubmUiA4gBAZIBF3BlcmZvcm1pbmdfYXJ0c190aGVhdGVyqgEQEAEqDCIIdGjDqWF0cmUoBA&phdesc=vesblXgVHgs&rlst=f#rlfi=hd:;si:5011719011781109502,l,Chhnb29nbGUgdGjDqWF0cmUgbGF1c2FubmUiA4gBAZIBF3BlcmZvcm1pbmdfYXJ0c190aGVhdGVyqgEQEAEqDCIIdGjDqWF0cmUoBA,y,vesblXgVHgs;mv:[[46.5380022,6.665280699999999],[46.5106222,6.5815857]];tbs:lrf:!1m4!1u3!2m2!3m1!1e1!1m4!1u2!2m2!2m1!1e1!2m1!1e2!2m1!1e3,lf:1,lf_ui:1" target="_blank"
        role="button"
        ><i class="fab fa-google"></i
      ></a>

      <!-- Instagram -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #ac2bac; color:white;"
        href="https://www.instagram.com/theatredevidy/" target="_blank"
        role="button"
        ><i class="fab fa-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #0082ca; color:white;"
        href="https://www.linkedin.com/search/results/all/?keywords=actor&origin=TYPEAHEAD_ESCAPE_HATCH" target="_blank"
        role="button"
        ><i class="fab fa-linkedin-in"></i
      ></a>
      <!-- Github -->
      <a
        class="btn btn-primary btn-floating m-1"
        style="background-color: #333333; color:white;"
        href="https://github.com/Ichenn92/peruname" target="_blank"
        role="button"
        ><i class="fab fa-github"></i
      ></a>
    </div>
    <div>
      Your performance is presented with <i class="fas fa-heart"></i> by
      <a href="#"> LeDernierRail.
    </div>
</a>
  </div>
  <!-- Copyright -->
</footer>

app/views/shared/_full-filter-form.html.erb
<div class="sidebar translated-down" id="sidebar">
  <div class="sidebar-container">
    <button class="btn btn-light btn-lg" id="button-close"><i class="fas fa-times" id="symbol-filter"></i></button>

    <div class="sidebar-scrollable">
      <div class="full-filter-bar container">
        <%= form_tag performances_search_path, id: "filter-form", method: :get do %>
          <h3>Basic options</h3>
          <%= label_tag "Lieu" %>
          <%= text_field_tag :address,
                             params[:address],
                             class: "form-control algolia-places-custom",
                             placeholder: "Choose a location" %>
          <%= label_tag "Univers du charactère" %>
          <%= collection_select :performance, :character_category,
                                CharacterCategory.all,
                                :id, :name,
                                { prompt: "Category", include_blank: "All", selected: params[:performance][:character_category] },
                                { class: "form-control" } %>
          <%= label_tag "Style de performance" %>
          <%= collection_select :performance, :performance_category,
                                PerformanceCategory.all,
                                :id, :name,
                                { prompt: "Acting category", selected: params[:performance][:performance_category] },
                                { class: "form-control" } %>

          <h4 class="mt-4">Pick date and time</h4>
          <%= label_tag "Date" %>
          <%= text_field_tag :date,
                             params[:date],
                             as: :string,
                             class: "datepicker form-control",
                             placeholder: "Pick a date" %>
          <%= label_tag "Start time" %>
          <%= time_select :performance,
                          :availability_start_time,
                          { prompt: true, ignore_date: true, discard_minute: true, selected: params[:performance]["availability_start_time(4i)"].blank? ? nil : params[:performance]["availability_start_time(4i)"].to_i },
                          { class: "form-control" } %>
          <%= label_tag "End time" %>
          <%= time_select :performance,
                          :availability_end_time,
                          { prompt: true, ignore_date: true, discard_minute: true, selected: params[:performance]["availability_end_time(4i)"].blank? ? nil : params[:performance]["availability_end_time(4i)"].to_i },
                          { class: "form-control" } %>

        <% end %>
        <br>
        <br>
      </div>
    </div>

    <input type="submit" value="Submit" form="filter-form" class="btn btn-primary w-100" id="btn-submit-filter">
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
  <%= image_tag "logo.png" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Search a Performance", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My upcoming bookings", "/bookings/my_bookings", class: "nav-link" %>
        </li>
        <% if current_user.actor %>
        <li class="nav-item">
          <%= link_to "My upcoming contracts", " /bookings/my_performances", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My performances", performances_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to new_performance_path, class: "nav-link mr-3" do %>
          <i class="fas fa-plus"></i> <i class="fas fa-theater-masks text-medium"></i>
      <% end %>
    </li>

    <% end %>
    <li class="nav-item dropdown">

    <% if current_user.photo.key.nil? %>
      <%= cl_image_tag("default_profile_um6sky.jpg", :default_image => "default_profile_um6sky.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
    <% else %>
      <%= cl_image_tag current_user.photo.key, width: 40, height: 40, crop: :thumb, gravity: :face, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-expanded': false %>
    <% end %>

    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
      <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
      <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
    </div>
    </li>
    <% else %>
      <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      </li>
    <% end %>
  </ul>
</div>
</div>

app/views/shared/_search-form.erb
    <div class="search-bar">

      <form action="/categories" class="form-inline padded mt-30">
        <input type="text" class="form-control" placeholder="Where?">
        <select name="categories" id="" class="form-control border-radius input-lg">
          <option selected>Categories</option>
          <option value="1">Celebrity</option>
          <option value="2">Superhero</option>
          <option value="3">Anime</option>
          <option value="4">Fake friend</option>
          <option value="5">Others</option>
        </select>
        <input type="text" name="start-time" class="form-control" placeholder="Start Time">
        <input type="text" name="end-time" class="form-control" placeholder="End Time">
        <input type="submit" class="btn btn-dark" value="Search">
      </form>
    </div>

app/views/shared/_search-form.html.erb
<div class="search-bar">

  <%= form_tag performances_search_path, class: "form-inline", method: :get do %>
    <%= text_field_tag :address,
                       params[:address],
                       class: "form-control",
                       placeholder: "Choose a location" %>
    <%= collection_select :performance, :character_category,
                          CharacterCategory.all,
                          :id, :name,
                          { prompt: "All categories" },
                          { class: "form-control" } %>
    <%= submit_tag "Search", class: "btn btn-dark btn-search" %>
  <% end %>
  
</div>