config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  get "performances/search"
  resources :performances
  put "users/settings"

  resources :bookings, only: [:index, :create] do
    post "/confirm", to: "bookings#confirm"
    post "/reject", to: "bookings#reject"
  end
  get "bookings/my_bookings"
  get "bookings/my_performances"
end

app/models/performance.rb
class Performance < ApplicationRecord
  reverse_geocoded_by "locations.latitude", "locations.longitude"

  belongs_to :user
  belongs_to :character
  belongs_to :location

  has_one :character_category, through: :character
  belongs_to :performance_category

  has_one_attached :photo
  has_many :bookings, dependent: :delete_all

  accepts_nested_attributes_for :location

  validates :user, presence: true
  validates :character, presence: true
  validates :character_category, presence: true
  validates :location, presence: true
  validates :price_per_hour, presence: true

  scope :all_my_performances, ->(user) { where("user_id = ?", user.id) }

  def self.search_near_performances_with_filter(params)
    search_radius = 5
    performances = Performance.joins(:location).near(params[:address], search_radius)

    if params[:performance][:character_category].present?
      performances = performances.joins(:character_category).where(character_category: { id: params[:performance][:character_category] })
    end

    if params[:performance][:performance_category].present?
      performances = performances.where(performance_category: params[:performance][:performance_category])
    end

    if params[:performance]["availability_start_time(4i)"].present? && params[:performance]["availability_end_time(4i)"].present?
      start_time = Tod::TimeOfDay::new(params[:performance]["availability_start_time(4i)"].to_i)
      end_time = Tod::TimeOfDay::new(params[:performance]["availability_end_time(4i)"].to_i)

      if start_time < end_time
        shift = Tod::Shift.new(start_time, end_time)
        performances = performances.select do |performance|
          actor = performance.user
          actor_shift = Tod::Shift.new(actor.availability_start_time, actor.availability_end_time)
          actor_shift.contains? shift
        end
      end

      if params[:date].present?
        shift
        performances = performances.select do |performance|
          performance.bookings.none? do |booking|
            if booking.date == params[:date] && booking.status == 2
              booking_shift = Tod::Shift.new(booking.start_time, booking.end_time)
              shift.overlaps?(booking_shift)
            end
          end
        end
      end
    end

    performances
  end

  # TODO: add validation of user where actor is true
  # TODO: add validation that price_per_hour is an integer > 10

end

app/controllers/performances_controller.rb
class PerformancesController < ApplicationController
  include Pundit
  skip_before_action :authenticate_user!, only: [:search, :show]
  skip_after_action :verify_authorized, only: [:search, :show]

  def search
    @performances = Performance.search_near_performances_with_filter(params)

    return no_result_found if @performances.empty?

    result_found
    set_markers
  end

  def index
    @performances = policy_scope(Performance).all_my_performances(current_user)
  end

  def show
    authorize @performance = Performance.find(params[:id])
    authorize @booking = Booking.new
  end

  def new
    if current_user.actor?
      authorize @performance = Performance.new
    end
  end

  def create
    if current_user.actor?
      set_attributes
      authorize @performance = Performance.new({ description: @description,
                                                 price_per_hour: @price_per_hour,
                                                 character: @character,
                                                 character_category: @character_category,
                                                 performance_category: @performance_category,
                                                 location: @location,
                                                 user: current_user })
      if @performance.save
        @performance.photo.attach(@photo)
        redirect_to performance_path(@performance)
      else
        render :new
      end
    end
  end

  def edit
    if current_user.actor?
      authorize @performance = Performance.find(params[:id])
    end
  end

  def update
    set_attributes
    authorize @performance = Performance.find(params[:id])
    @performance.update(description: @description) unless @description.nil?
    @performance.update(price_per_hour: @price_per_hour) unless @price_per_hour.nil?
    @performance.update(character: @character) unless @character.nil?
    @performance.update(character_category: @character_category) unless @character_category.nil?
    @performance.update(performance_category: @performance_category) unless @performance_category.nil?
    @performance.update(location: @location) unless @location.nil?
    unless @photo.nil?
      @performance.photo.purge
      @performance.photo.attach(@photo)
    end
    redirect_to performances_path
  end

  def destroy
    authorize @performance = Performance.find(params[:id])
    @performance.destroy
    redirect_to performances_path
  end

  private

  def set_attributes
    @character = Character.find(performance_params[:character_id].to_i) unless performance_params[:character_id].blank?
    @character_category = CharacterCategory.find(performance_params[:character_category].to_i) unless performance_params[:character_category].blank?
    @performance_category = PerformanceCategory.find(performance_params[:performance_category_id].to_i) unless performance_params[:performance_category_id].blank?
    @description = performance_params[:description] unless performance_params[:description].blank?
    @location = Location.find_or_create_by(name: params[:location][:name], address: params[:location][:address])
    @price_per_hour = performance_params[:price_per_hour] unless performance_params[:price_per_hour].blank?
    @photo = params[:performance][:photo]
  end

  def no_result_found
    flash[:alert] = "No result found with those parameters"
    redirect_back fallback_location: root_path
    # render "pages/home"
  end

  def result_found
    flash[:success] = "Matches found!"
  end

  def set_markers # the `geocoded` scope filters only flats with coordinates (latitude & longitude)
    if @performances
      @markers = @performances.map do |performance|
        {
          lat: performance.location.latitude,
          lng: performance.location.longitude,
          infowindow: render_to_string(partial: "info_window", locals: { performance: performance }),
        }
      end
    end
  end

  def performance_params
    params.require(:performance).permit(:character_id, :character_category, :performance_category_id, :description, :price_per_hour, :photo)
  end
end

app/views/performances/_card_performance.html.erb
<%= link_to performance_path(performance) do %>
  <div class="row m-0 border-bottom">

    <div class="col-xs-12 col-sm-5 p-0 images-presentation">
      <div class="h-100 p-3 image-container">
        <% if performance.photo.attached? %>
          <%# raise %>
          <%= cl_image_tag performance.photo.key, height: 300, width: 400, crop: :fill %>
        <% else %>
          <img src=<%= "https://source.unsplash.com/400x300/?#{performance.character.name}" %> />
        <% end %>
      </div>
      <div class="ranking">
        <h2 class="text-mode-gradient brand-color text-small">
          grand-master
        </h2>
      </div>
    </div>

    <div class="col-xs-12 col-sm-7 p-0">
      <div class="h-100 d-flex flex-column justify-content-between px-3 py-3">
        <div class="d-flex justify-content-between align-items-start pb-2">
          <div>
            <p>interpreted by: <%= performance.user.nickname %></p>
            <h2 class="text-medium">
              <%= performance.character.name %>
            </h2>
          </div>
          <% if performance.user.photo.attached? %>
            <%= cl_image_tag(performance.user.photo.key, width: 150, height: 150, crop: :thumb, gravity: :face, class: "avatar-bordered") %>
          <% else %>
            <%= cl_image_tag("default_profile_um6sky.jpg", :default_image => "default_profile_um6sky.jpg", class: "avatar-bordered") %>
          <% end %>
        </div>

        <br>

        <div class="text-small text-thin">
          <%= performance.description.truncate(120) %>
        </div>

        <br>

        <div class="d-flex justify-content-between align-items-end pt-2">
          <p><i class="fas fa-star d-none"></i></p>
          <div class="text-small">
            <span class="text-bold">
              CHF <%= performance.price_per_hour %>
            </span>
            <span class="text-regular">
              /hour
            </span>
          </div>
        </div>

      </div>
    </div>

  </div>
<% end %>

app/views/performances/_form.html.erb
<%= simple_form_for @performance do |f| %>
    <%= f.association :character, include_blank: "<Select a character>" %>
    <%= f.input :character_category, collection: CharacterCategory.all, include_blank: "<Select a character category>" %>
    <%= f.association :performance_category, include_blank: "<Select a performance category>" %>
    <%= f.input :description, placeholder: "<Enter a description...>" %>
    <%= simple_fields_for :location do |p| %>
        <%= p.input :name, :label => "Location Name", placeholder: "Exemple: Café de la Gare" %>
        <%= p.input :address, class: "form-control", placeholder: "Choose a location", input_html: { id: "address" } %>
    <% end %>
    <%= f.input :price_per_hour, placeholder: "<Enter a price per hour...>" %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Submit performance", class: "btn btn-primary" %>
<% end %>

app/views/performances/_info_window.html.erb
<%= link_to performance_path(performance) do %>
  <div class="row m-0 border-bottom">

    <div class="h-100 d-flex flex-column justify-content-between px-3 py-3">
      <div class="d-flex justify-content-between align-items-start pb-2">
        <div>
          <p>interpreted by: <%= performance.user.nickname %></p>
          <h2 class="text-medium">
            <%= performance.character.name %>
          </h2>
            <% 3.times do %>
              <i class="fas fa-star text-small"></i>
            <% end %>
        </div>
        <%= cl_image_tag performance.user.photo.key, width: 40, height: 40, crop: :thumb, gravity: :face, class: "avatar-bordered" %>
      </div>

      <br>

      <div class="text-small text-thin">
        <%= performance.description %>
      </div>

      <br>

      <div class="text-small text-regular">
        <%= performance.location.address %>
      </div>

      <br>

      <div class="d-flex justify-content-between align-items-end pt-2">
        <div class="text-small">
          <span class="text-bold">
            CHF <%= performance.price_per_hour %>
          </span>
          <span class="text-regular">
            /hour
          </span>
        </div>
      </div>
  </div>
<% end %>

app/views/performances/edit.html.erb
<div class="container p-4">
  <h1>Update performance: <%= @performance.character.name %></h1>
  <%= render 'form' %>
</div>

app/views/performances/index.html.erb
<div class="container my-4">
  <div class="bookings-list">
    <div class="container m-2">
      <h1>All my Performances</h1>
    </div>
    <div class="container" id="performances-column">
      <ul class="cards-performance full-height-without-navbar">
        <% @performances.each do |performance| %>
          <li class="card-performance my-4">
            <div class="d-flex">
              <div class="flex-grow-1">
                <%= render partial: "card_performance", locals: { performance: performance } %>
              </div>
              <div class="d-flex flex-column justify-content-start">
                <%= link_to edit_performance_path(performance), class: "btn btn-warning btn-lg text-white d-flex align-items-center rounded mt-3 mr-3", style: "height: 50px; width: 50px;" do %>
                  <i class="fas fa-edit"></i>
                <% end %>
                <%= link_to performance_path(performance), method: "delete", data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-lg text-white d-flex align-items-center rounded mt-3 mr-3", style: "height: 50px; width: 50px;" do %>
                  <i class="fas fa-trash-alt"></i>
                <% end %>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/performances/new.html.erb
<div class="container p-4">
  <h1>Create a performance</h1>
  <%= render 'form' %>
</div>

app/views/performances/search.html.erb
<button class="btn btn-light btn-lg btn-map" id="button-switch-map"><i class="text-big fas fa-map-marked-alt" id="symbol-switch-map"></i></button>
<button class="btn btn-light btn-lg btn-map" id="button-filter"><i class="text-big fas fa-filter" id="symbol-filter"></i></button>

<div class="d-flex m-0 position-relative">

  <div class="d-lg-block p-0" id="performances-column">
    <ul class="cards-performance full-height-without-navbar">
      <% @performances.each do |performance| %>
        <li class="card-performance">
          <%= render partial: "card_performance", locals: { performance: performance } %>
        </li>
      <% end %>
    </ul>
  </div>

  <div class="flex-grow-1 d-none d-lg-block map-container full-height-without-navbar"
      id="map"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV["MAPBOX_API_KEY"] %>">
  </div>

</div>

<%= render "shared/full-filter-form" %>

app/views/performances/show.html.erb
<div class="performance-show-container">

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url('<%= cl_image_path @performance.photo.key, crop: :fill %>')">
    <div class="title-show text-center">
      <h1><%= @performance.character.name %> by <%= @performance.user.nickname %></h1>
      <p><%= @performance.location.address %></p>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-8">
        <div class="performance-show-card">
          <h2><%= @performance.character.name %></h2>
          <p>Universe: <%= @performance.character_category.name %></p>
          <p><%= @performance.description %></p>
          <h5>Availabilities</h5>
          <p><%= @performance.user.availability_start_time.strftime("%I:%M %p") %> to <%= @performance.user.availability_end_time.strftime("%I:%M %p") %></p>
        </div>
        <div class="performance-show-card">
          <h3>Details</h3>
          <div class="d-flex align-items-center justify-content-between">
            <div>
              <i class="fas fa-theater-masks"></i><span> <%= @performance.performance_category.name %></span>
            </div>
            <div class="text-small">
              <span class="text-bold">
                CHF <%= @performance.price_per_hour %>
              </span>
              <span class="text-regular">
                /hour
              </span>
            </div>
          </div>
        </div>
        <div class="performance-show-card">
          <div class="flex-align">
            <h6 class="no-mb">Share</h6>
            <div class="d-flex">
              <i class="fab fa-facebook-f fa-2x mr-2"></i>
              <i class="fab fa-twitter-square fa-2x mr-2"></i>
              <i class="fas fa-envelope-square fa-2x mr-2"></i>
            </div>
          </div>
        </div>
      </div>
      <%= render "bookings/form" %>
    </div>
  </div>
</div>